#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format

npm run lint || (
    echo "Lint failed, please fix the errors before committing."
    exit 1
)

npm run build || (
    echo "Build failed, please fix the errors before committing."
    exit 1
)

echo "You win this time 🎉 .Committing this code now"
